### ISSUE TITLE
carousel arrows do not work

### ISSUE THREAD

**Issue by ililush** [Zero-to-Heroes/overwolf-replay-app#47]
Hi, i've tried installing the new version (14) but that does not fix the issue.

**Comment by sebastientromp** [comment]
Possibly an issue when displaying exactly 4 games because of an index mismatch:

î`				this.showBottomArrow = (this.firstDisplayedGameIndex + this.numberOfDisplayedGames) < thumbnailElements.length - 1;` 

at https://github.com/Zero-to-Heroes/overwolf-replay-app/blob/master/Files/src/js/components/carousel.component.ts (the `-1` should probably not be there)

**Comment by sebastientromp** [comment]
And that's it :) Fix will be available in the next release
